spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/authdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mail:
    host: localhost
    port: 1025
    username: dezzy
    password: dezzy
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  thymeleaf:
    prefix: classpath:/templates/

application:
  security:
    jwt:
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8300